### ISSUE TITLE
Office and Windows ETW Providers: Sensitivity

### ISSUE THREAD

**Issue by rayfo** [microsoft/MSO-Scripts#4]
I am reviewing the sensitivity of the providers in WPRP\OfficeProviders.wprp and WindowsProviders*.wprp and Defender*.wprp

I ran these on Win11:

`logman query providers`

`wpr –providers`

`xperf -providers`

###   WindowsProviders*.wprp: ###
Confirmed that all these providers are public by name except:

o   ^* EP_Windows_Info=487D6E37-…

o   ^* EP_AppLifeCycle-UI=ee97cdc4-…

o   ^* EP_Helium_C2RX=5526aed1-…

o   ^* EP_DiagTrackA=43AC453B-…

o   ^* EP_DiagTrackB=56DC463b-…

o   ^* EP_HangReporting=3e0d88de-…

o   ^* EP_FaultReporting=1377561d-…

o   ^* EP_ErrorReporting=cc79cf77-…

o   \* EP_Windows_AssessmentExecutionEngine=6fe1cbf0-… [Microsoft-Windows-AssessmentExecutionEngine]<br/>
(Deprecated? Don’t remember why I thought this one important.)

###  Defender*.wprp: ###
Confirmed: all these providers are public by name except:

o   \* EP_AM_UI=911F2490-…

o   \* EP_SENSE=FAE96D09-…

o   \* EP_SenseIR=B6D775EF-…

o   ^# EP_NWActivity=28DCC28B-…  [Microsoft.Windows.Secuity.CodeIntegrity.NWActivity]<br/>
(Using dot(.) instead of dash(-) in the name by convention indicates TraceLogging instead of Manifest.)

o   ^# EP_NWActivityV=3A82F218-…  [Microsoft.Windows.Secuity.CodeIntegrity.NWActivityVerbose]

**<u>LEGEND</u>**

**^** GUID shows up unnamed: xperf -providers

**\*** Publicly available at github projects [such as this one](https://github.com/repnz/etw-providers-docs/blob/master/FullProviderList) or [this one](https://gist.github.com/mattifestation/04e8299d8bc97ef825affe733310f7bd) or [this one](https://github.com/kacos2000/Queries/blob/master/providers.txt).

**\#** Somebody knows about these: [referenced only here](https://n4r1b.com/posts/2022/09/smart-app-control-internals-part-2/)

<br/>
 

###  OfficeProviders.wprp: ###

For OfficeProviders, I had done a search of the Office code base for all available ETW providers thinking that would be useful for internal users.  That’s how they I know of their existence.

Most (not all) of the Office ETW providers are manifest-free TraceLogging providers.

They do not show up as registered providers (xperf -providers), and they mostly do not show up in online searches.

Take for example this one: Microsoft.Office.Common {8A3A9FD4-… } which includes HVAs and the like.  No public documentation or acknowledgement.

I suspect that a majority of those in the original OfficeProviders.wprp were in fact deprecated.  I ran this experiment, which enabled most everything in the original OfficeProviders.wprp (~50 providers):

`set WPT_WPRP=.\WPRP\OfficeProviders.wprp!OfficeLogging`

`TraceCPU Start`

_Launch Excel, Word, PowerPoint, OneNote, Outlook (classic); Open a file, etc.; Quit_

`TraceCPU Stop -WPA -fastsym`

The result was only these Office-specific providers:

o   SPP-Tracelog (unnamed; data doesn’t appear useful)

o   Microsoft-AppV-ServiceLog (unnamed; data doesn’t appear useful)

o   Microsoft-Office-Events  (CodeMarkers, etc.)

o   Microsoft-Office-Word

o   Microsoft-Office-Word2

o   Microsoft-Office-Word3

o   Microsoft.Office.Common (HVAs, etc.)

o   Microsoft.Office.CorrelationMetadata (Session ID, OfficeUserId, etc. – one record per app)

o   Microosft.Office.Excel (OpenDocumentBegin/Success)

o   Microsoft.Office.Measurements (FileIO, etc.)

o   Microsoft.Office.PowerPoint (OpenDocumentBegin/Success)

o   Microsoft.Office.SessionIdProvider (Similar to CorrelationMetadata, but much sooner)

o   Microsoft.Office.TelemetryEngine

o   OfficeAirSpace

o   OfficeLoggingLiblet

Very commonly used WPRP profile in WPRP\OfficeProviders.wprp!CodeMarkers

       <EventProviderId Value="EP_OLog_CodeMarkers" />

       <EventProviderId Value="EP_OLog_MeasureFIO" /> # a380209f-f500-586f-d5aa-1f15e23cefa5

       <EventProviderId Value="EP_OSessionIdProvider" />

       <EventProviderId Value="EP_OCorrelationMetadata" /> # fc15139c-ddf2-481f-9a9b-365919cb8ae5

       <EventProviderId Value="EP_OTelemetryEngine" /> # d1318fe0-16b7-4f5b-b5f9-ba3cd54cd9cc

       <EventProviderId Value="EP_OCommon_HVA" /> 

       <EventProviderId Value="EP_Excel" /> # 6FD91573-4ABC-43A5-84EE-ACB8DC42888F

       <EventProviderId Value="EP_PowerPoint" /> # 71B8AC9B-04B7-4216-82C0-DD54FEE06D2C

       <EventProviderId Value="EP_Extensibility" />

       

       <EventProviderId Value="EP_AppLifeCycle-UI" />

       <EventProviderId Value="EP_Helium_C2RX" />

       <EventProviderId Value="EP_KernelProcess" />

       <EventProviderId Value="EP_Windows_Kernel_Process" />

<br/> 

## SUMMARY: ETW PROVIDERS ##

All of the Windows and Defender ETW providers in the WPRPs can be found via at least one of these:

•         With name and GUID on Win11, using LogMan or WPR or XPerf

•         With GUID only, using XPerf

•         By searching GitHub projects [such as this one](https://github.com/repnz/etw-providers-docs/blob/master/FullProviderList) or [this one](https://gist.github.com/mattifestation/04e8299d8bc97ef825affe733310f7bd) or [this one](https://github.com/kacos2000/Queries/blob/master/providers.txt)

•         [Referenced only in one random blog](https://n4r1b.com/posts/2022/09/smart-app-control-internals-part-2/) (CodeIntegrity.NWActivity*)

The Office ETW providers in the WPRPs are mostly dynamic (TraceLogging) and many in the original OfficeProviders.wprp were probably deprecated.

For the public audience, I have removed the more obscure ones, particularly since I do not see them producing useful events.

## ISSUES ##

**Q:** What are your thoughts on this? Are any of these particularly sensitive?  Any that should be excluded?

**Comment by Leonid-Zakharov** [comment]
I'm closing this issue as right now we are not planning to make any changes in the set of tracked providers.
